default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: proficiency-test_development

test:
  <<: *default
  database: proficiency-test_test

production:
  <<: *default
  database: proficiency-test_production
